#!/bin/sh

# This script displays disk usage statistics in human format
# in an improved, faster way over "du -hs"

echo""
echo "Non-hidden files and directories"
echo "--------------------------------"
du -sk ./* | sort -n | awk 'BEGIN\
                                 { pref[1]="K"; pref[2]="M"; pref[3]="G";} \
                                 { total = total + $1; x = $1; y = 1; while( x > 1024 )\
                                 { x = (x + 1023)/1024; y++; } printf("%g%s\t%s\n",int(x*10)/10,pref[y],$2); }\
                             END\
                                 { y = 1; while( total > 1024 ) { total = (total + 1023)/1024; y++; }\
                             printf("Total: %g%s\n",int(total*10)/10,pref[y]); }'
echo""
echo "Hidden files and directories"
echo "----------------------------"
du -sk ./.* | sort -n | awk 'BEGIN\
                                  { pref[1]="K"; pref[2]="M"; pref[3]="G";} \
                                  { total = total + $1; x = $1; y = 1; while( x > 1024 )\
                                  { x = (x + 1023)/1024; y++; } printf("%g%s\t%s\n",int(x*10)/10,pref[y],$2); }\
                              END\
                                  { y = 1; while( total > 1024 ) { total = (total + 1023)/1024; y++; }\
                              printf("Total: %g%s\n",int(total*10)/10,pref[y]); }'
